### ISSUE TITLE
github actions should expose just branch name

### ISSUE THREAD

**Issue by maxheld83** [maxheld83/ghactions#340]

**Comment by maxheld83** [comment]
Emailed support:

> the github.head_ref is a little unwieldy, giving something like 'refs/heads/master'.
>
> I get that that's technically correct, but just "master" would be easier, and is what I guess most users are after.
> 
>It's a bit cumbersome having to strsplit the result first.
> 
>Perhaps expose something that just gives the branch name as an alternative?

**Comment by maxheld83** [comment]
this can now be easily done by github actions expressions

**Comment by brettstack** [comment]
@maxheld83 could you elaborate? How do you transform `refs/head/master` into `master`?

**Comment by maxheld83** [comment]
I'm just using some shell action in a separate step; several solutions are listed here: https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
