### ISSUE TITLE
Ubuntu 18:04 E: Package 'openjdk-7-jre-headless' has no installation candidate

### ISSUE THREAD

**Issue by pachamaltese** [maxheld83/ghactions#383]
even when adding the PPA, gh-actions fails on ubuntu because of a moved package, see for reference https://github.com/jbkunst/highcharter/actions

**Comment by pachamaltese** [comment]
here's the full log https://pipelines.actions.githubusercontent.com/qRRHc1vhtDzk0t7TC64ygmt8HWnMZFfY8tG9YseDWOYHayGHqz/_apis/pipelines/1/runs/39/signedlogcontent/5?urlExpires=2020-02-24T19%3A04%3A43.7587600Z&urlSigningMethod=HMACV1&urlSignature=prcZ%2F6tSMZ04%2BhUp4bs7d%2BwnFiMMnf%2FSDxkCghTNcSo%3D

**Comment by pat-s** [comment]
https://github.com/r-hub/sysreqsdb/issues/70

JDK is pre-installed, no need to install jdk-7 which is not avail on bionic.

Comment out the "sysreqsdb" action.
