### ISSUE TITLE
Error: 'ui_warn' is not an exported object from 'namespace:usethis'

### ISSUE THREAD

**Issue by gorkang** [maxheld83/ghactions#64]
When trying to use this for a project I encountered the error: 

> Error: 'ui_warn' is not an exported object from 'namespace:usethis'

I did: 
```
devtools::install_github("maxheld83/ghactions")
library(ghactions)
ghactions::use_ghactions(workflow = website())
```
Cheers!

**Comment by maxheld83** [comment]
Sorry this pkg started out with a frustration for you!

We are currently using a recent dev version of [usethis](https://usethis.r-lib.org), which *does* export`ui_warn()`, though the current cran version does not.

`devtools::install_github("maxheld83/ghactions")` *should* solve this problem and download the required dev version of usethis for you.

You might see some dialogue as the following:

```
Downloading GitHub repo maxheld83/ghactions@master
These packages have more recent versions available.
Which would you like to update?

1:   usethis (70d473467... -> fbb03d11a...) [GitHub]

Enter one or more numbers separated by spaces, or an empty line to cancel
```

You always want to confirm that you *do* want to install the dev version of usethis.

Sometimes, it's also necessary to restart the R session (RStudio > Session > Restart R).

Can you check whether installing again *with* the usethis dev version solves your problem?`

If not, could you paste your `sessionInfo()`?

**Comment by maxheld83** [comment]
obviously, relying on the dev version of usethis is suboptimal, and we'll go to their CRAN version asap, as per #65, but this could be a couple of weeks/months, depending on the usethis dev cycle.

**Comment by gorkang** [comment]
No worries! I appreciate what you are doing. Just wanted to let you know so other people won't encounter it.

As you said, restarting the session solved the problem! Thanks fur such a prompt answer.

Maybe adding that as a step in the README may help others? Just before "Because you're likely only to ever use it once, you need not take on ghactions as a dependency in your projects."?

Thanks again!
