### ISSUE TITLE
Possible areas to work on

### ISSUE THREAD

**Issue by jimhester** [maxheld83/ghactions#98]
- [ ] Action to run devtools::document() on a repo and commit any changes (if any) -> #102 
- [ ] Action to run styler::style_pkg() on a repo and add commit any changes (if any).
- [ ] Action to run clang-format on a repo and add commit any changes (if any).

- [ ] Action to run goodpractice::goodpractice() on a repo and add results as comments to a PR / commit.
- [ ] Action to run lintr::lint_package() on a repo and add results as comments to a PR / commit. (#90)

- [ ] Action to run pkgdown::build_site() on a repo and push changes to gh-pages branch.
- [ ] Action to run covr::codecov() on a repo (only if build passed) and send results to codecov or (may need modifications to covr).

**Comment by maxheld83** [comment]
That's a great list of actions specific for pkg dev; I'm going to track them all in duplicate #2, and will break them down into smaller sub-issues.
